// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFS7Jpq2R3ntrdM213nlbYNHWmlXc9hqI',
    appId: '1:68853883528:web:45eccb43307932a297f53d',
    messagingSenderId: '68853883528',
    projectId: 'flutter-book-36439',
    authDomain: 'flutter-book-36439.firebaseapp.com',
    storageBucket: 'flutter-book-36439.appspot.com',
    measurementId: 'G-D2FZ36928V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACmyg51y1LXzcObigShpqhLLyAZoevh8A',
    appId: '1:68853883528:android:e20dd31668135bb697f53d',
    messagingSenderId: '68853883528',
    projectId: 'flutter-book-36439',
    storageBucket: 'flutter-book-36439.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZBAzcTpc2yCNUsZIX8GR8Erjd9kuT4yA',
    appId: '1:68853883528:ios:d7184c2a798c98ca97f53d',
    messagingSenderId: '68853883528',
    projectId: 'flutter-book-36439',
    storageBucket: 'flutter-book-36439.appspot.com',
    iosClientId: '68853883528-gnbp5sae76g0c8qckv148q58nv9kpgot.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZBAzcTpc2yCNUsZIX8GR8Erjd9kuT4yA',
    appId: '1:68853883528:ios:d7184c2a798c98ca97f53d',
    messagingSenderId: '68853883528',
    projectId: 'flutter-book-36439',
    storageBucket: 'flutter-book-36439.appspot.com',
    iosClientId: '68853883528-gnbp5sae76g0c8qckv148q58nv9kpgot.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookDemo',
  );
}
